//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemindMe.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemindMe.Core.Localization.fr-FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date selectionnée est déjà passée.
        /// </summary>
        internal static string date_time_not_past_error {
            get {
                return ResourceManager.GetString("date_time_not_past_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jour.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette action supprimera tous les anciens rappels, souhaitez-vous continuer ?.
        /// </summary>
        internal static string delete_past_reminders_confirm_message {
            get {
                return ResourceManager.GetString("delete_past_reminders_confirm_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer les anciens rappels.
        /// </summary>
        internal static string delete_past_reminders_confirm_title {
            get {
                return ResourceManager.GetString("delete_past_reminders_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette action supprimera le rappel, souhaitez-vous continuer ?.
        /// </summary>
        internal static string delete_reminder_confirm_message {
            get {
                return ResourceManager.GetString("delete_reminder_confirm_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le rappel.
        /// </summary>
        internal static string delete_reminder_confirm_title {
            get {
                return ResourceManager.GetString("delete_reminder_confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heure.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mois.
        /// </summary>
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date est obligatoire.
        /// </summary>
        internal static string reminder_date_required {
            get {
                return ResourceManager.GetString("reminder_date_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;heure est obligatoire.
        /// </summary>
        internal static string reminder_time_required {
            get {
                return ResourceManager.GetString("reminder_time_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le titre est obligatoire.
        /// </summary>
        internal static string reminder_title_required {
            get {
                return ResourceManager.GetString("reminder_title_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconde.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dans {0} {1}.
        /// </summary>
        internal static string time_future {
            get {
                return ResourceManager.GetString("time_future", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a {0} {1}.
        /// </summary>
        internal static string time_past {
            get {
                return ResourceManager.GetString("time_past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
